### PR TITLE
Fix coap_resolve_address_info() for LWIP

### LINKED ISSUE #1734: LWIP without OS-awareness produces a compile errors
This software library is a masterpiece, 😎 and we decided to use it under extreme conditions on a minimalist IoT controller. However, we encountered an unexpected problem: it's impossible to compile libcoap for the tiny STM32 with LWIP 2.1.2 but without OS-awareness (i.e., without FreeRTOS). 😔

The functions and constants `getaddrinfo()`, `AF_UNSPEC`, `AF_INET` etc. are undefined when a LWIP is used (`WITH_LWIP` = 1) but without an OS-awareness (`NO_SYS` = 1) and dependly without a Sockets API (`LWIP_SOCKET` = 0). The first compile error goes there: `coap_address.c:coap_resolve_address_info()`. Moreover the `struct addrinfo` can be also undefined by `LWIP_DNS` = 0.

As a quick and dirty workaround, the following code can be added to the user's  `coap_config.h` file:

```
#if WITH_LWIP && NO_SYS

#define AF_UNSPEC       0
#define AF_INET         2

#define getaddrinfo(nodname, servname, hints, res) \
   lwip_getaddrinfo(nodname, servname, hints, res)

typedef uint32_t in_addr_t;

struct in_addr {
  in_addr_t s_addr;
};

struct addrinfo {
  int               ai_flags;      /* Input flags. */
  int               ai_family;     /* Address family of socket. */
  int               ai_socktype;   /* Socket type. */
  int               ai_protocol;   /* Protocol of socket. */
  uint32_t          ai_addrlen;    /* Length of socket address. */
  struct sockaddr  *ai_addr;       /* Socket address of socket. */
  char             *ai_canonname;  /* Canonical name of service location. */
  struct addrinfo  *ai_next;       /* Pointer to next in list. */
};

struct sockaddr_in {
  uint8_t         sin_len;
  uint8_t         sin_family;
  uint16_t        sin_port;
  struct in_addr  sin_addr;
#define SIN_ZERO_LEN 8
  char            sin_zero[SIN_ZERO_LEN];
};

#endif /* WITH_LWIP && NO_SYS */
```
By the way, the `check_function_exists(getaddrinfo HAVE_GETADDRINFO)` call is used in the CMakeLists.txt file, but the result is not used anywhere.

I humbly hope that someone will be able to adapt the library for the above conditions in the right way.

### PR DESCRIPTION
**Pull request by raspopov**
These changes add a basic implementation of the `coap_resolve_address_info()` function when compiling LWIP with `NO_SYS = 1`. This implementation is similar to those in CONTIKI and RIOT.

The function `gai_strerror()` was removed because it is not very important, yet it is missing from many implementations.

A CONTIKI compilation bug has also been fixed.

Fixes #1734.

### CODE REVIEW

File: src/coap_address.c [hunk 1]
```diff
@@ -876,12 +951,24 @@ coap_resolve_address_info(const coap_str_const_t *address,
...
+                          uint16_t ws_port,
+                          uint16_t ws_secure_port,
+                          int ai_hints_flags,
+                          int scheme_hint_bits,
+                          coap_resolve_type_t type) {
   return NULL;
-#endif
 }
 
+#endif
```
Comment (mrdeep1) [inline src/coap_address.c:976]: I think I prefer the #bad to be here so a new platform will throw up a compile warning rather that having to debug an address that is not parsing.

File: src/coap_address.c [hunk 2]
```diff
@@ -643,7 +696,7 @@ coap_resolve_address_info(const coap_str_const_t *address,
   error = getaddrinfo(addrstr, NULL, &hints, &res);
 
   if (error != 0) {
-    coap_log_warn("getaddrinfo: %s: %s\n", addrstr, gai_strerror(error));
+    coap_log_warn("getaddrinfo: %s: %d\n", addrstr, error);
```
Comment (mrdeep1) [inline src/coap_address.c:700]: My preference would be to still have `gai_strerror()` to translate the `getaddrinfo()` that will have more meaning to most developers.  It is also used elsewhere in the code.

I agree that some platforms do not support `gai_strerror()` and stub functions have had to be written.

**Review by mrdeep1 — COMMENTED** [review]
Thanks for fixing this.

Please squash your merges into one.
